name: Push model to Replicate

on:
  workflow_dispatch: {}  # تا هر وقت خواستی دستی اجراش کنی

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Cog CLI (dev build)
        run: |
          curl -L -o /usr/local/bin/cog https://github.com/replicate/cog/releases/download/v0.9.0-beta.1/cog_Linux_x86_64
          chmod +x /usr/local/bin/cog
          cog --version

      - name: Login to Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          echo "$REPLICATE_API_TOKEN" | cog login --token-stdin

      - name: Push model to Replicate
        run: |
          cog push r8.im/danial-k-f/saxmorpher
