name: Push model to Replicate

on:
  workflow_dispatch: {}

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Cog CLI
        run: |
          python -m pip install --upgrade pip
          python -m pip install cog==0.16.8
          python -m cog --version

      - name: Login and Push to Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          # Login to Replicate
          python -m cog login --token "$REPLICATE_API_TOKEN"

          # Push model
          python -m cog push r8.im/danial-k-f/saxmorpher
