name: Push model to Replicate

on:
  workflow_dispatch: {}

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Cog CLI from official source
        run: |
          curl -o /usr/local/bin/cog -L https://github.com/replicate/cog/releases/download/v0.8.6/cog_Linux_x86_64
          chmod +x /usr/local/bin/cog
          cog --version

      - name: Login to Replicate and Push model
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          cog login --token "$REPLICATE_API_TOKEN"
          cog push r8.im/danial-k-f/saxmorpher
